baseURL = "http://example.org/"
languageCode = "es-es"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = "Portfolio"
    title = "Esther Guzmán"
    author = "Darshan Baral"
    description = " Desarrolladora web"
    copyright = "@copyright"
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Esther Guzmán"
        photo = "images/mar.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "#"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "#"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "#"
        title = "ResearchGate"		

    # Education section
    [params.education]
        title = "Educación"

        [[params.education.list]]
        degree = "Grado Superior de Desarrollo de aplicaciones web (DAW)"
        college = "CPIFP Los Enlaces"
        dates = "2021 - 2023"
        


    # Languages section
    [params.language]
        title = "Idiomas"

        [[params.language.list]]
        language = "Inglés"
        level = "Medio"
				
        [[params.language.list]]
        language = "Chino"
        level = "Básico"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Aprender cosas nuevas"
		
		[[params.hobbies.list]]
        interest = "Música"

        [[params.hobbies.list]]
        interest = "Viajar"

        [[params.hobbies.list]]
        interest = "Cocinar"

    [params.aboutme]
        description = "Desarrolladora web con ..."

    # Experiences section
    [params.experiences]
        title = "Experiencia"

        [[params.jobs.list]]
        position = "Junior Front-end Developer"
        dates = "Marzo(2022) - *Presente*.(FCT)"
		link = "https://www2.deloitte.com/es/es/footerlinks/office-locator/Oficinas-de-Deloitte-en-Espana/zaragoza.html"
        company = "Deloitte"

        

    # Projects section
    [params.projects]
        title = "Proyectos"

        [[params.projects.list]]
        title = "Proyecto Libros"
        url = "https://drive.google.com/drive/folders/1ph-L_0UYYx4_zshrrZhTqr57LlhRc5ND"
        description = "Programa de Java que simula una web de libros, en la que puedes crear guardar y visualizar libros y autores..."
		
		[[params.projects.list]]
        title = "Proyecto web empresa ACME"
        url = "https://estherdeleon.github.io/acme/"
        description = "Desarrollo total de una web para la empresa ACME, con tecnologías como markdown, toml y git."
    # Skills section
    [params.skills]
        title = "Conocimientos"

        [[params.skills.list]]
        skill = "HTML5"
        skillrating = 95 # out of 100
                
        [[params.skills.list]]
        skill = "CSS3"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "Java"
        skillrating = 70
